### PR TITLE
🚑 Fix Hidden Service V3 Client Authorization

### PR DESCRIPTION
**Pull request by Psykopear**
# Proposed Changes

This PR fixes the creation of a stealth tor hidden service V3.

I made the following changes:

**Dockerfile**
- Use latest TOR version
- Install openssl to generate the key pair on the server
- Install coreutils for the `base64` and `base32` commands needed later

**Scripts**
- Create the directory for authorized_clients inside 20-dirs.sh
- Updated the config to V3 hidden services following the documentation found at: https://community.torproject.org/onion-services/advanced/client-auth/

## Related Issues
#104

### CODE REVIEW

**Comment by foo-calls-bar** [comment]
I don't see what the point in removing the "HiddenServiceVersion 3" line is, or how it doesn't break normal public v3 hidden service access.

**Comment by Psykopear** [comment]
> I don't see what the point in removing the "HiddenServiceVersion 3" line is, or how it doesn't break normal public v3 hidden service access. Is it simply set to 3 by default in the proposed Tor update or something? Please explain.

Hi,
I removed the line because it is not mentioned anymore in the [Tor documentation](https://community.torproject.org/onion-services/setup/), and I tried with or without it and it did not seem to have any effect, Tor starts the V3 version by default.

I went and checked the [Changelog](https://raw.githubusercontent.com/torproject/tor/main/ChangeLog) in the tor repository, and in fact the `HiddenServiceVersion` defaults to `3` since version `0.3.5`, so this setting shouldn't be needed.

If you prefer to have it anyway to be clear about what version we are using, I can add it back.

**Comment by frenck** [comment]
> Good point, if the repo is actively maintained it should not be a problem to have pinned dependencies.

Pinning is needed to leverage Docker caching properly.

**Comment by Psykopear** [comment]
> Pinning is needed to leverage Docker caching properly.

Uh, didn't think about that, you are absolutely right. I just pushed the fix.

**Comment by sveip** [comment]
Great work @Psykopear. I'm wondering how you foresee migration work for existing installs? Is a remove and install needed, or will an upgrade path be present?

**Comment by Psykopear** [comment]
> Great work @Psykopear. I'm wondering how you foresee migration working for existing installs? Is a remove and install needed, or will an upgrade path be present?

Hi, thank you for pointing this out.

I didn't try to update since I recently had a fresh install of hassio's server.
At least the url and client keys will change, but I should check if something else breaks.

To be sure I'll try to install the currently published version and then upgrade to this one and see what happens.
I'll update this post once I know the answer.

**Comment by foo-calls-bar** [comment]
> To be sure I'll try to install the currently published version and then upgrade to this one and see what happens. I'll update this post once I know the answer.

I tried but the versions of tor, openssl, and coreutils you pinned prevented a clean upgrade without slight modification:
 `RUN apk add --no-cache tor=0.4.5.10-r0 openssl=1.1.1l-r0 coreutils=8.32-r2`
allows upgrade and working v3 authentication on my HA core-2021.10.4 & OS 6.5. Will upgrade those soon and test as well.

**Comment by Psykopear** [comment]
> > To be sure I'll try to install the currently published version and then upgrade to this one and see what happens. I'll update this post once I know the answer.
> 
> I tried but the versions of tor, openssl, and coreutils you pinned prevented a clean upgrade without slight modification: `RUN apk add --no-cache tor=0.4.5.10-r0 openssl=1.1.1l-r0 coreutils=8.32-r2` allows upgrade and working v3 authentication on my HA core-2021.10.4 & OS 6.5. Will upgrade those soon and test as well.

Hi @foo-calls-bar , I'm sorry but I haven't find the time to test this yet.
I should be able to do it this week, but if you want, feel free to open a PR over my fork with the fixes needed to make the upgrade from previous versions of the addon possible, so we can move on with this PR.

**Comment by sveip** [comment]
@Psykopear, if there is anything that I can do to test, let me know.

**Comment by GuillaumeHubR** [comment]
Hi guys,

New to HA (comming from jeedom), I can view a beautifull and well done project, congrats.

This feature is pretty interesting, could you quickly explain me how to deploy this change ? And did you know how much time to wait before upgrading Tor the add-on version ?

Regards Guillaume

**Comment by Psykopear** [comment]
> @Psykopear, if there is anything that I can do to test, let me know.

Hi sveip, what I'd like to do is:
- Locally install the currently published version of the Tor addon.
- Configure it and start the service.
- Upgrade to the version in this PR.
- Check what's causing the upgrade to fail (as foo-calls-bar noticed).
- Update the scripts to detect if a previous version of the addon was installed, and change what's needed to make it work with the latest versions of the packages.
- If this is not possible/too hard to do, pin the packages to the versions foo-calls-bar suggested, and repeat the checks to ensure the upgrade goes smooth.

**Comment by sveip** [comment]
Is it possible to do when running with hassos and addons in the official containers?

**Comment by Psykopear** [comment]
> Is it possible to do when running with hassos and addons in the official containers?

Yes, that's what I'm doing.

What I did is (following the tutorial on how to create you first addon):
- Ssh into the server running hassos
- create a folder `addons` inside `/root`
- `git clone https://github.com/psykopear/addon-tor.git`
- `cd addon-tor`
- `git checkout fix-issue-104`

Then I think you have to restart the server, and the addon will be listed under "Local addons" in the addon store.
Here is a screenshot:
image


Now, I'm testing the process myself:
- Uninstalled the local add on
- Checkout the tag `v3.0.5`, which should be the latest released version.
- Restart the home assistant server and install the local addon at the `v3.0.5` version.
This fails:
```
The command '/bin/bash -o pipefail -c apk add --no-cache tor=0.4.4.8-r0' returned a non-zero code: 1
```

I guess this is the same problem foo-calls-bar was having, in reverse.
I'm not sure how to proceed here, it might be related to the packages caching system, but I don't exactly know how everything works in home assistant so I might need some help here.
I'd like to see the error message so I can try to understand what's going on.

Also, trying to install the official addon works, that's why I think the problem is not in the code but in the existing container/cache

**Comment by sinclairpaul** [comment]
This isn't anything to do with package caching/Home Assistant, but how alpine version packages.

Your build error is:

```
ERROR: unable to select packages:
  coreutils-8.32-r2:
    breaks: world[coreutils=9.0-r1]
  openssl-1.1.1l-r0:
    breaks: world[openssl=3.0.0-r2]
  tor-0.4.5.10-r0:
    breaks: world[tor=0.4.6.7-r0]
```

Alpine package versions can be seen at <https://pkgs.alpinelinux.org/packages>, the version depends on the version of base you are targetting, as a hint:

```
        tor=0.4.5.10-r0 \
        coreutils=8.32-r2
```
(I believe OpenSSL is already in the base).

**Comment by GuillaumeHubR** [comment]
OK Guy,

I made some change localy and it works without any error and increase the private key usage.
Will view to upload new version on soon.

**Comment by Psykopear** [comment]
> OK Guy,
> 
> I made some change localy and it works without any error and increase the private key usage. Will view to upload new version on soon.

Hi @GuillaumeHubR , if you have a working patch, feel free to open a PR directly on [my fork](https://github.com/Psykopear/addon-tor/tree/fix-issue-104) so your commits will be on top of this same PR

**Comment by GuillaumeHubR** [comment]
11 days ago I made change and send a pull request i was unable to find this time :(
No worries.

Good news image have been updated in V11 and tor 0.4.6 is now on the installation, will check how v3 and hiddenservices is implemented, and if necessary will create the branch from the main.

**Comment by sveip** [comment]
@Psykopear, after the PR from @GuillaumeHubR, is this good to go?

**Comment by Psykopear** [comment]
@sveip Yes, it should be.

@frenck could you let the CI run, and maybe make a final review of the PR?

**Comment by aitor3ml** [comment]
> @sveip Yes, it should be.
> 
> @frenck could you let the CI run, and maybe make a final review of the PR?

+1

**Comment by sveip** [comment]
Is there anything holding this back that we can work through? If not, would be fantastic to have this merged.

**Comment by GuillaumeHubR** [comment]
Hi Guy, 
I know I'm not the most active on this threat but the patch is working for me now since months ago.
Really appreciate integrate this feature in official add-on vs local use.
@frenck what do we need to do to validate this change ?

**Comment by snowyu** [comment]
Maybe The [DOCS.md](https://github.com/Psykopear/addon-tor/blob/fix-issue-104/tor/DOCS.md) should be changed appropriately. 

btw, howto get/change the private key?

**Comment by snowyu** [comment]
still report error: `The command '/bin/bash -o pipefail -c apk add --no-cache tor=0.4.6.9-r1 openssl=1.1.1m-r1 coreutils=9.0-r2' returned a non-zero code: 2`

**Review by frenck — APPROVED** [review]
Thanks, @Psykopear 👍

**Pull request merged**
